Added backup state recording to ldap and mysql backup scripts

diff --git a/roles/mysql/templates/mysql-backup.sh.j2 b/roles/mysql/templates/mysql-backup.sh.j2
--- a/roles/mysql/templates/mysql-backup.sh.j2
+++ b/roles/mysql/templates/mysql-backup.sh.j2
@@ -14,14 +14,26 @@ MYSQLDUMP="`${WHICH} mysqldump`"
 DATEC="`${WHICH} date`"
 FIND="`${WHICH} find`"
 DATE=`${DATEC} +%Y-%m-%d`
-
 DATABASES=`mysql --defaults-file=/etc/mysql/debian.cnf -Bse 'show databases'`
+FAILFILE="/var/local/backups/MYSQL_FAIL"
 
 for db in ${DATABASES}; do
     if [[ "${db}" != "information_schema" ]] && [[ "$db" != "performance_schema" ]] && [[ "${db}" != "mysql" ]] && [[ "${db}" != _* ]] ; then
         ${MYSQLDUMP} --databases $db > ${BACKUPDIR}/${DATE}_${db}_db.sql
+	STATE="$?"
+	if [ "$STATE" != "0" ]
+	then
+	    echo "MYSQL BACKUP FAILED"
+	    echo "FAIL" > $FAILFILE
+	else
+	    echo "MYSQL BACKUP SUCCEDED"
+	fi
     fi
 done
 
-${FIND} "${BACKUPDIR}" -type f ! -name '*.gz' -mtime +0 -exec gzip {} \;
-${FIND} "${BACKUPDIR}" -type f -mtime +29 -delete
+if [ "$STATE" == "0" ]
+then
+    echo "REMOVE OLD BACKUPS"
+    ${FIND} "${BACKUPDIR}" -type f ! -name '*.gz' -mtime +0 -exec gzip {} \;
+    ${FIND} "${BACKUPDIR}" -type f -mtime +30 -delete
+fi
diff --git a/roles/openldap/templates/ldap-backup.sh.j2 b/roles/openldap/templates/ldap-backup.sh.j2
--- a/roles/openldap/templates/ldap-backup.sh.j2
+++ b/roles/openldap/templates/ldap-backup.sh.j2
@@ -16,8 +16,16 @@ LDAPSEARCH="`${WHICH} ldapsearch`"
 DATEC="`${WHICH} date`"
 FIND="`${WHICH} find`"
 DATE=`${DATEC} +%Y-%m-%d`
+FAILFILE="/var/local/backups/LDAP_FAIL"
 
 ${LDAPSEARCH} -QLLLY EXTERNAL -H ldapi:/// -b ${BASEDN} ${FILTER} cn sn givenName schacPersonalUniqueID mail eduPersonEntitlement eduPersonAffiliation userPassword schacExpiryDate pwdAccountLockedTime objectClass > ${BACKUPDIR}/${DATE}_ldap-users.ldif
 
-${FIND} "${BACKUPDIR}" -type f ! -name '*.gz' -mtime +0 -exec gzip {} \;
-${FIND} "${BACKUPDIR}" -type f -mtime +30 -delete
+if [ $? -ne 0 ]
+then
+    echo "LDAP BACKUP FAILED"
+    echo "FAIL" > $FAILFILE
+else
+    echo "LDAP BACKUP SUCCEDED"
+    ${FIND} "${BACKUPDIR}" -type f ! -name '*.gz' -mtime +0 -exec gzip {} \;
+    ${FIND} "${BACKUPDIR}" -type f -mtime +30 -delete
+fi
